tools:
  
  arachni:
    host: http://0.0.0.0
    port: 7331
    context: scans
      
  w3af:
    host: http://0.0.0.0
    port: 5000
    context: scans/

  zap:
    host: http://0.0.0.0
    port: 8081
    context: JSON/
